name: uber_pro
description: A professional ride sharing application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  dio: ^5.3.3
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  image_picker: ^1.0.4
  signature: ^5.4.0
  google_maps_flutter: ^2.5.0
  camera: ^0.11.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/